### PR TITLE
New externs, in the npm folder.

### PR DESCRIPTION
**Pull request by dionjwa**
Here are a bunch of externs I've written for various projects. I'd like to add them to a central repo.

I've used the 'js.npm' package instead of the 'js.node' as per a previous discussion on the mailing list.

### CODE REVIEW

**Comment by dionjwa** [comment]
Also, I don't think it makes sense to have separate folders for extern files that are a single file.

**Comment by Simn** [comment]
Can we be 100% certain that they remain single file in the future? It might be safer to use directories for that reason alone otherwise.

**Comment by dionjwa** [comment]
We can't be 100%, but it's pretty unlikely a given npm project will suddenly increase its complexity to require multiple files. 

Honestly I really dislike folders with a single file as a default, because it is extra work for nothing, and extra code (longer packages). If the any of those become more complex, then the extra refactor required for the longer package name will likely be the smallest concern of a refactor of that magnitude.

**Comment by andyli** [comment]
Externs for different lib should be in a different package. It is because it is very likely to have multiple libs define types of the same name. Name conflicts happen when types of the same name exist in the same package, even if they are in different files (modules).

**Comment by dionjwa** [comment]
Closing, new pull request with fixed package names.

**Pull request closed without merging**
